### ISSUE TITLE
CUC - Custom Upgrade Registry error

### ISSUE THREAD

**Issue by millerlarson** [raiguard/Factorio-SmallMods#1]
Attempting to play with custom upgrade registry lists/tables.

I'm unclear on the difference between the upgrade registry (what are all the defaults?), and the custom registry...  Not sure on syntax for multiple tables, etc...
But I've gotten the following error several times:
![image](https://user-images.githubusercontent.com/7883766/70872338-3d0dfa80-1f5c-11ea-9128-b1ebde6bcff1.png)

I believe I was trying the following when the above error happened:
`{['medium-electric-pole'] = 'big-electric-pole', ['big-electric-pole'] = 'substation'}{['wooden-chest'] = 'iron-chest', ['iron-chest'] = 'steel-chest'}{['pipe'] = 'pipe-to-ground', ['pipe-to-ground'] = 'storage-tank', ['storage-tank'] = 'pump'}`

**Comment by raiguard** [comment]
Get rid of the separated tables and put them in one table. Sorry if that wasn't clear, I'll update the tooltip to be a bit more descriptive, and put a slightly more detailed guide in the FAQ on the mod page.

Here's what it should look like:
```
{['medium-electric-pole'] = 'big-electric-pole', ['big-electric-pole'] = 'substation', ['wooden-chest'] = 'iron-chest', ['iron-chest'] = 'steel-chest', ['pipe'] = 'pipe-to-ground', ['pipe-to-ground'] = 'storage-tank', ['storage-tank'] = 'pump'}
```

Let me know if you have any other questions!

**Comment by millerlarson** [comment]
That is awesome, thanks!
Is there anyway to get a list of what the mod does include as "upgradable" ?

**Comment by raiguard** [comment]
The mod dynamically calculates what is upgradable by default by reading the game's entity prototypes when you load the game. Whatever you put into the custom registry overwrites whatever the mod found in the game itself. If you wish to see what the mod generated, type this command into the console:

`/c __CursorUpgradeCarousel__ game.print(serpent.line(global.registry))`

This will produce a **_very long_** message that will contain the entire upgrade registry. You could replace `serpent.line` with `serpent.block` to improve readability, but then it would go off the top of the screen and you wouldn't be able to see the whole thing.

**Comment by millerlarson** [comment]
Thanks for the help and the great mod! All good here.
