### ISSUE TITLE
Transport Belt Madness results in an error:

### ISSUE THREAD

**Issue by Spook2U** [raiguard/Factorio-SmallMods#10]
I get this message: 

> The mod Quickbar Templates (1.0.3) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event QuickbarTemplates::on_configuration_changed
> __QuickbarTemplates__/control.lua:3: attempt to index local 'player' (a nil value)
> stack traceback:
> 	__QuickbarTemplates__/control.lua:3: in function 'create_gui'
> 	__QuickbarTemplates__/control.lua:131: in function <__QuickbarTemplates__/control.lua:127>

**Comment by raiguard** [comment]
Sorry for the delay, I've released a fix.
