### ISSUE TITLE
Error on entering sandbox scenario

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-SmallMods#11]
Hello, I use a sandbox scenario from the map editor button on the main menu to test and design layouts. When I added the quickbartemplates mod to the mod pack I use during testing I received the following error when trying to load the sandbox.

https://imgur.com/a/69cutwW

**Comment by raymundfueloep** [comment]
Can confirm: Happens when loading a scenario in the map editor.

**Comment by raiguard** [comment]
Sorry for the delay, I've released a fix.
