### ISSUE TITLE
Error when trying to change JSON table

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-SmallMods#13]
I got this error after trying to enter a custom upgrade path and messing up the JSON table format.

Somehow it saved as a setting (not 100% sure if it was due to saving a game or not) and then when re-launching Factorio I got the error while loading.

Only thing I could do to make it go away was to delete the mod-settings.dat file and start over. This was a pain as it meant I lost all my other mod settings also with no way to just reset the settings for just Cursor Upgrade Carousel alone.

After some trial and error of working out how to overcome the error I wasn't able to reproduce it trying to follow the same steps as I thought I had done the first time. So therefore this report may not be all that useful to you as it could have been a one off just for me?

Perhaps make it so that if a custom JSON table is entered incorrectly, don’t keep what has been incorrectly entered in the settings. Have it switch back to the default so as to not give it a chance to save to the mod-settings.dat file thus making the whole file unusable while CUC is enabled.

Let me know if you think the corrupted settings file would be worthwhile to you and I can send it along.

`The mod Cursor Upgrade Carousel (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event CursorUpgradeCarousel::on_runtime_mod_setting_changed (ID 59)
__CursorUpgradeCarousel__/control.lua:38: bad argument #1 of 2 to 'pairs' (table expected, got string)
stack traceback:
	[C]: in function 'pairs'
	__CursorUpgradeCarousel__/control.lua:38: in function 'apply_registry_overrides'
	__CursorUpgradeCarousel__/control.lua:87: in function <__CursorUpgradeCarousel__/control.lua:85>`

**Comment by raiguard** [comment]
Thanks, I've fixed this for the next release.

**Comment by Tealc-1899** [comment]
Thats great, thanks for the fast reply!

May I ask what was the cause of the error? Was it related the the incorrect JSON format?

I did it another error too but it was so similar I assume it is related.

The mod Cursor Upgrade Carousel (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event CursorUpgradeCarousel::on_init()
__CursorUpgradeCarousel__/control.lua:38: bad argument #1 of 2 to 'pairs' (table expected, got string)
stack traceback:
	[C]: in function 'pairs'
	__CursorUpgradeCarousel__/control.lua:38: in function 'apply_registry_overrides'
	__CursorUpgradeCarousel__/control.lua:67: in function 'refresh_registries'
	__CursorUpgradeCarousel__/control.lua:82: in function <__CursorUpgradeCarousel__/control.lua:74>

**Comment by Tealc-1899** [comment]
I forgot to mention that I had issues adding rail to an upgrade path.

I kept getting a message that I had an "incorrect entry name".

I tried both the Prototype name and Internal name... Is this a bug or a limitation.

{"rail-planner": "rail-signal", "rail-signal": "rail-chain-signal"}

EDIT: Worked out that it should be "straight-rail' and not just "rail"
