### ISSUE TITLE
Mod description clarity

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-SmallMods#14]
So it took me a little while to work out that the mod will work on any of the default upgrade items in the game (including Assembling Machines) but more specifically Inserter>Fast Inserter>Stack Inserter.

Maybe it should have been obvious but I think I may have been mislead by your demo video showing the upgrading of belts etc. I assumed it only worked on belts then you had to define other upgrades in order to get the power poles etc as in the second demo video.

The first thing I tried to add for my own upgrades for were inserters. However I entered the JSON table incorrectly and got the error message  “Invalid string formatting – the string must represent a valid JSON table” telling me as such. But yet I was still able to switch the inserters, albeit without the Long Handed Inserter. I had just assumed it had missed the long inserter but the others (ie the default inserter upgrades) were still working.

So it very much confused me for a little while before I worked it all out. A suggestion of maybe making a note on the mod page that it will work by default for any items in game that have their own upgrade paths or ie anything that would work with the upgrade planner purely just for clarity.

**Comment by raiguard** [comment]
I thought the description was clear enough, but I can rework it to make it a bit better. Thanks for the suggestion!

**Comment by Tealc-1899** [comment]
Yes, it is pretty clear I was just being thick I guess lol
Thanks for taking it on board.
