### ISSUE TITLE
Different upgrade paths

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-SmallMods#15]
I think its great that the belts can switch from Transport Belt>Fast Transport Belt>Express Transport Belt by default but in my playing I tend to find I do more switching from Transport Belt>Underground Belt>Splitter.

However when I enter my own upgrade path for Transport Belt>Underground Belt>Splitter I lose the ability to still switch between Transport Belt>Fast Transport Belt>Express Transport Belt when I need too, albeit not as often.

It would be great if the default and custom upgrades would work with SHIFT+Mousewheel and then have Transport Belt>Fast Transport Belt>Express Transport Belt work with CTL+Mousewheel.

Of course thats what would work best for my play style so maybe an option to reverse the above example as well as changing the shortcuts if required.

No idea if thats possible or not. Maybe primary and secondary upgrade paths? Belts are the only use case I can think of where the two different upgrade paths may be wanted so maybe its not worth the effort.

Currently I would have to use a second mod such as “OSHA Hot Swap” to have the two different upgrade paths on different keybinds present at the same time. Hence why it would be great if it could be done in the one mod.

**Comment by raiguard** [comment]
I've been considering something like this for a while, and will eventually implement it. When I do, it'll probably be as a new mod, since it won't strictly be about upgrades anymore (and Cursor Upgrade Carousel is a terrible name, I don't know why I ever used it...).

This will come hand-in-hand with a GUI for editing the settings.

**Comment by Tealc-1899** [comment]
Thats great news! I very much look forward to these changes/new mod.

**Comment by raiguard** [comment]
Cursor Upgrade Carousel was replaced with [Cursor Enhancements](https://github.com/raiguard/Factorio-CursorEnhancements). During development of that mod I attempted to expand the cursor scrolling feature, but it ended up being extremely unwieldy, so it still works very similarly to how CUC did. However, mods can now add their own default overrides, so it is a bit fancier.
