### ISSUE TITLE
GUI for Upgrade Paths

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-SmallMods#16]
Entering the JSON table feels clunky and not very user friendly.

It would be great if there was an in game GUI where custom upgrade paths could be assigned. A single box for each item in the upgrade path. Clicking on an empty box brings up the default item menu to select the desired item.

As an example, what has been set up in the other mod “OSHA Hot Swap”. But I am sure with your style and polish your implementation for far exceed Hot Swap.

Sorry for the noisy spam. I am done for now 😂

**Comment by raiguard** [comment]
This will eventually be added.

**Comment by Tealc-1899** [comment]
Awesome, can't wait! Thanks for all your effort.

**Comment by raiguard** [comment]
Cursor Upgrade Carousel was replaced with [Cursor Enhancements](https://github.com/raiguard/Factorio-CursorEnhancements). I toyed with creating a GUI, but it turned out to be a lot more complicated than it was worth.
