### ISSUE TITLE
Invalid entity name in custom upgrade registry - Cursor Upgrade Carousel

### ISSUE THREAD

**Issue by Tealc-1899** [raiguard/Factorio-SmallMods#17]
I have been unable to add the following items to the custom upgrade paths.

red-wire
green-wire
copper-cable
stone-brick
concrete
hazard-concrete
refined-concrete
refined-hazard-concrete

**Comment by raiguard** [comment]
Those are items and tiles, not entities.

CUC is being deprecated in favor of a new mod, Cursor Enhancements. That mod will let you switch between any item you want, and will be configurable.
