### ISSUE TITLE
Crash when using Puzzletory

### ISSUE THREAD

**Issue by KrazyTygr** [raiguard/Factorio-SmallMods#18]
I get this error: 
The mod Quickbar Templates (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickbarTemplates::on_configuration_changed
__QuickbarTemplates__/control.lua:3: attempt to index local 'player' (a nil value)
stack traceback:
	__QuickbarTemplates__/control.lua:3: in function 'create_gui'
	__QuickbarTemplates__/control.lua:131: in function <__QuickbarTemplates__/control.lua:127>

It happened after I started playing the Puzzletory scenario.

**Comment by raiguard** [comment]
Sorry for the delay, I've released a fix.
