### ISSUE TITLE
Desync issue in multiplayer when server is stopped while clients are still connected

### ISSUE THREAD

**Issue by azaghal** [raiguard/Factorio-SmallMods#19]
If a server is stopped while there are still connected players (via the `/quit` command in console), and then additional mods are introduced prior to starting it again, connecting clients will fail to connect, and be presented with 

**Reproduction steps**

1. Start a headless server.

2. Start a client.

3. Connect to the server.

4. Search for items via *Quick Item Search*.

5. Stop the server in the server console using the `/quit` command.

6. Enable a new mod or disable an existing one on both server and client.

7. Start the server again.

8. Connect to the server.

9. Search for items via *Quick Item Search*.

10. Disconnect from the server.

11. Connect to server once again.

**Expected results**

1. In step **4** it is possible to search for items via *Quick Item Search*.

2. In step **9** it is possible to search for items via *Quick Item Search*.

2. In step **11** it is possible to connect to the server.

** Actual results**

1. In step **4** it is possible to search for items via *Quick Item Search*.

2. In step **9** it is *not* possible to search for items via *Quick Item Search*. User is presented with the error message `Cannot open Quick Item Search, dictionary translation has not yet finished`. This persists no matter how long you wait.

3. In step **11** it is *not* possible to connect to the server. User is presented with the following error:

```
Cannot join. The following mod event handlers are not identical between you and server. This indicates that the following mods are not multiplayer (save/load) safe. (See the log file for more details):

mod-QuickItemSearch
```

The log file on client side contains the following error message:

```
 124.102 Error ClientMultiplayerManager.cpp:1108: mod-QuickItemSearch was registered for the following events when the map was saved but has not re-registered them as a result of loading: on_tick (ID 0)
 124.102 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-QuickItemSearch"
 124.102 Info ClientMultiplayerManager.cpp:578: UpdateTick(7964) changing state from(ConnectedLoadingMap) to(Failed)
```

**Additional notes**

After doing quite a bit of digging, I ran into an interesting behaviour of Factorio in regards to the `LuaPlayer::connected` property. Namely, if the server is stopped while there are still clients connected, during the execution of handlers registered via `LuaBootstrap::on_configuration_changed` their state remains `connected`.

Unfortunately, this seems to be the [intended behaviour](https://forums.factorio.com/viewtopic.php?p=502608), which in my opinion means it must not be relied on during the `LuaBootstrap::on_configuration_changed` handler execution.

On the *Quick Item Search*, the code effectively registers the `on_tick` handler during `LuaBootstrap::on_configuration_changed` if the player is connected (via `player_data.refresh`). This works as intended during single player, but causes an issue in multiplayer in above scenario.

The issue in step **9** comes from the fact that `LuaPlayer::request_translation` can only be used on connected players, and does nothing if player is not connected. Although the property reports player as connected, the player is not really connected at that point. So, in spite of translation requests being sent off, they can never be fulfilled, and the mod remains in the "waiting for translation to finish" state (because it never really receives any translations), and it remains with the registered `on_tick` handler.

Once the player disconnects in step **10**, the game is saved, *with* the registered `on_tick` handler.

Upon the player reconnecting, the `on_tick` handler will not get registered on the client side, but it is registered server side, resulting in the listed error.

**Comment by azaghal** [comment]
Now, as for resolving this, I tried decoupling a bit the logic for the `player_data.refresh` to be more granular, but in the end it did not help simply because of how the single player and multiplayer have a bit of a difference in handling the player joins. E.g. in single player it seems like player joins only once during the lifetime of a savegame, so that event cannot be relied on to trigger translation dictionary rebuild.

One thing that popped to my mind to fix this problem is to mark all players as requiring to redo the translations during the `LuaBootstrap::on_configuration_changed`, then register an initial "one-off" `on_tick` handler that will essentially trigger the translation process for all currently connected users (to handle the single player mode), deregister itself, and invoke `on_tick.update` at that point.

But, I'm not really sure if that's a good way to go about it.

**Comment by raiguard** [comment]
Thanks for the detailed report. However, this is the wrong repository! It was my bad for not updating the link after I moved QIS to its own repository.

Could you please re-post this issue in the [QIS repository](https://github.com/raiguard/Factorio-QuickItemSearch)?

**Comment by azaghal** [comment]
Done :)
