### ISSUE TITLE
Quickbar templates, Import not working

### ISSUE THREAD

**Issue by cloudziq** [raiguard/Factorio-SmallMods#20]
Factorio 1.0 version,   When starting a new game,  default Quickbar is not loaded,  also selecting Blueprint with QuickBar saved,  does not show that little import button as before,  exporting seems fine (when holding an empty blueprint in hands)

Update,  import button shows when blueprint is in the players inventory,  but nothing happens after clicking it

**Comment by Dominiquini** [comment]
I can confirm that this bug happens to me too!

**Comment by raiguard** [comment]
Unfortunately I cannot fix this because currently, there is no way for mods to read what is called a "blueprint record" - a blueprint that is stored in the library. From the mod's point of view, the cursor stack is empty. I have made a [modding interface request](https://forums.factorio.com/88185) to enable this capability.

If the request is rejected, there will be literally nothing I can do about this. Here's hoping that the devs will respond!

In the meantime, you have to drop the blueprint into your inventory and pick it up again so it's an actual item. Only then will the mod be able to read it.

**Comment by cloudziq** [comment]
but it's also not working when picking it up from inventory. Button to import shows this way, but clicking it gives no result

**Comment by raiguard** [comment]
Ah, my apologies, I'll look into it.

**Comment by hahoyer** [comment]
Probably this code can help. If you not already have fixed it.

<details><summary>Excerpt</summary>

```lua
-- create the GUI
local function create_gui(player)
  local window = player.gui.screen.add {type = "frame", name = "qt_window", style = "quick_bar_window_frame"}
  local inner_panel = window.add {type = "frame", name = "qt_inner_panel", style = "shortcut_bar_inner_panel"}
  local export_button =
    inner_panel.add {
    type = "sprite-button",
    name = "qt_export_button",
    style = "shortcut_bar_button_blue",
    sprite = "qt-export-blueprint-white",
    tooltip = {"qt-gui.export"}
  }
  local import_button =
    inner_panel.add {
    type = "sprite-button",
    name = "qt_import_button",
    style = "shortcut_bar_button_blue",
    sprite = "qt-import-blueprint-white",
    tooltip = {"qt-gui.import"}
  }
  window.visible = false
  return {window = window, export_button = export_button, import_button = import_button}
end

-- setup player global table and GUI
local function setup_player(player)
  local data = create_gui(player)
  global.players[player.index] = data
end

-- set window location relative to the player's quickbar
local function set_gui_location(player, window)
  local resolution = player.display_resolution
  local scale = player.display_scale
  window.location = {
    x = (resolution.width / 2) - ((56 + 258) * scale),
    y = (resolution.height - (56 * scale))
  }
end

local function modulo(n, d)
  local q, r = math.modf(n / d)
  r = math.floor(r * d + 0.5)
  return q, r
end

function IndexToPosition(index)
  local yIndex, xIndex = modulo(index - 1, 10)
  local result = {x = xIndex - 3.5, y = 4.5 - yIndex}
  return result
end

function PositionToIndex(position)
  local result = math.floor(position.x + 4) + math.floor(5 - position.y) * 10
  return result + 1
end

-- export the current quickbar filters to a blueprint
local function export_quickbar(player)
  -- get quickbar filters
  local get_slot = player.get_quick_bar_slot
  local filters = {}
  for i = 1, 100 do
    local item = get_slot(i)
    if item and item.name ~= "blueprint" and item.name ~= "blueprint-book" then
      filters[i] = item.name
    end
  end
  -- assemble blueprint entities
  local entities = {}
  for i = 1, 100 do
    -- add blank combinator

    entities[i] = {
      entity_number = i,
      name = "constant-combinator",
      position = IndexToPosition(i)
    }
    -- set combinator signal if there's a filter
    if filters[i] ~= nil then
      entities[i].control_behavior = {
        filters = {
          {
            count = 1,
            index = 1,
            signal = {
              name = filters[i],
              type = "item"
            }
          }
        }
      }
    end
  end
  return entities
end

-- apply the filters from the given blueprint to our quickbar
local function import_quickbar(player, entities)
  -- error checking: should have exactly 100 entities
  if #entities ~= 100 then
    player.print {"qt-message.invalid-blueprint"}
    return
  end
  -- assemble filters into a table
  local filters = {}
  for i = 1, 100 do
    local entity = entities[i]
    -- error checking: should be a constant combinator
    if entity == nil or entity.name ~= "constant-combinator" then
      player.print {"qt-message.invalid-blueprint"}
      return
    end
    -- get_blueprint_entities() does not return them in any particular order, so calculate the index by position
    local pos = entity.position
    local index = PositionToIndex(entity.position)
    if entity.control_behavior then
      -- error checking: should only have one filter
      if #entity.control_behavior.filters > 1 then
        player.print {"qt-message.invalid-blueprint"}
        return
      end
      filters[index] = entities[i].control_behavior.filters[1].signal.name
    else
      filters[index] = ""
    end
  end
  local length = #filters
  -- due to floating point imprecision, we must check if all of the indexes are off by one, and compensate if so
  local offset = length == 101 and -1 or 0
  local start = length == 101 and 2 or 1
  -- apply the filters
  local set_filter = player.set_quick_bar_slot
  for i = start, length do
    local filter = filters[i]
    if filter == "" then
      filter = nil
    end
    set_filter(i + offset, filter)
  end
end

-- EVENT HANDLERS

script.on_init(
  function()
    global.players = {}
    for _, player in pairs(game.players) do
      setup_player(player)
    end
  end
)

script.on_configuration_changed(
  function()
    for i, player_table in pairs(global.players) do
      player_table.window.destroy()
      local player = game.get_player(i)
      if player then
        global.players[i] = create_gui(player)
      else
        -- clean up unneeded tables
        global.players[i] = nil
      end
    end
  end
)

script.on_event(
  defines.events.on_player_created,
  function(e)
    local player = game.players[e.player_index]
    setup_player(player)
    -- apply default template if one is set up
    local template = player.mod_settings["qt-default-template"].value
    if template ~= "" then
      -- create inventory and insert a blueprint
      local inventory = game.create_inventory(1)
      inventory.insert {name = "blueprint"}
      local blueprint = inventory[1]

      -- import the default template
      if blueprint.import_stack(template) == 0 then
        -- apply to quickbar
        import_quickbar(player, blueprint.get_blueprint_entities())
      else
        -- error
        player.print {"qt-message.invalid-default-blueprint"}
      end

      -- destroy inventory
      inventory.destroy()
    end
  end
)

local function on_cursor_stack_changed(e)
  local player = game.players[e.player_index]
  local gui = global.players[e.player_index]
  local stack = player.cursor_stack
  if stack and stack.valid_for_read and stack.name == "blueprint" then
    -- show GUI
    set_gui_location(player, gui.window)
    if stack.is_blueprint_setup() then
      gui.export_button.visible = false
      gui.import_button.visible = true
    else
      gui.export_button.visible = true
      gui.import_button.visible = false
    end
    gui.window.visible = true
  elseif gui.window.visible then
    -- hide GUI
    gui.window.visible = false
  end
end
script.on_event(defines.events.on_player_cursor_stack_changed, on_cursor_stack_changed)

script.on_event(
  {defines.events.on_player_display_resolution_changed, defines.events.on_player_display_scale_changed},
  function(e)
    set_gui_location(game.players[e.player_index], global.players[e.player_index].window)
  end
)

script.on_event(
  defines.events.on_gui_click,
  function(e)
    if e.element.name == "qt_export_button" then
      local player = game.players[e.player_index]
      local stack = player.cursor_stack
      if stack and stack.valid_for_read and stack.name == "blueprint" then
        -- export to held blueprint
        stack.set_blueprint_entities(export_quickbar(player))
        -- update visible button
        on_cursor_stack_changed(e)
      end
    elseif e.element.name == "qt_import_button" then
      local player = game.players[e.player_index]
      local stack = player.cursor_stack
      if stack and stack.valid_for_read and stack.name == "blueprint" then
        -- import from held blueprint
        import_quickbar(player, stack.get_blueprint_entities())
      end
    end
  end
)
```

</details>

**Comment by raiguard** [comment]
Thanks, but unfortunately your fix doesn't work for all cases. The location of `{0,0}` in a blueprint is no longer trustworthy, and from my testing, apparently arbitrary. I can no longer rely on position to figure out which index a combinator refers to.

I am solving this problem by using "blueprint tags", in which I am simply storing the index that each combinator corresponds with. I should have done this from the beginning. This completely eliminates all position-related problems, but comes with two caveats:

- Existing template blueprints will no longer work
- You cannot place then re-select the blueprint to import it

While it's unfortunate that old templates will no longer work, this method is completely future-proof and is practically guaranteed never to break. I really should have done this from the beginning.

Because this change will break all existing templates, I am moving the mod version to 2.0.0. I'm really sorry for the inconvenience (believe me, I have a ton of templates that are now completely useless) but hopefully this should never happen again. Thanks for using the mod!

**Comment by raiguard** [comment]
I received a reponse from the developers, and as of the blueprint library redesign, the position of entities in a blueprint are literally just the coordinates they're at in the actual map when selected. So, yeah, you can't rely on position at all anymore unless you want to manually calculate the center of the blueprint.

**Comment by cloudziq** [comment]
Thanks for the fix, old templates not working is not a big problem anyway, We can start over ^.^

**Comment by hahoyer** [comment]
Actually I don't understand. The code I sent to you is working. You could use it at least to keep the old blueprints working.
There is nothing magic. They just shifted a blueprint by 0.5 in x and y direction. I tested this also with manually created constant combinator arrays.

**Comment by raiguard** [comment]
Just tested it:

![image](https://user-images.githubusercontent.com/3515394/90651592-6c1af100-e1fa-11ea-9372-6c8e5bf4bfd4.png)

It works fine if you don't select combinators from the world, but as soon as you do, it crashes. The problem is, the position of blueprint entities used to be centered around the center of the blueprint. Now they just keep whatever position they had when you select them.

The blueprint tags system is more stable and future-proof so I am sticking with it. Thank you for your input, though!

**Comment by hahoyer** [comment]
Oh, sorry. Meanwhile I found this problem too. 
Now I implemented a better version: 
See here: (https://github.com/hahoyer/factorio/blob/master/mods/QuickbarTemplates-1-0-0/source/control.lua)

**Comment by raiguard** [comment]
Thanks for your efforts! However, I am not going to re-implement position-based indexing. I already released the new version with tags yesterday, which is both far more efficient and far more streamlined than position-based. I'm sorry about the backwards incompatibility, but like I said, the new system should _never_ break and is far more reliable.

**Comment by hahoyer** [comment]
My new version has been implemented on top of your last version. So the nice position based thing is already in there.
In addition it provides the ability to use any 10x10 array of constant-combinators like in the old version. 
Just have a look at the algorithm I used. It is really simple.

**Comment by raiguard** [comment]
I apologize for being a jerk about this, I'm getting off my high horse and re-introducing position-based indexing. Thank you for your contribution!
