### ISSUE TITLE
Quickbar Templates blank filters

### ISSUE THREAD

**Issue by DonGufo** [raiguard/Factorio-SmallMods#22]
First of all the in game blueprint manipulation is working beautifully.

Regarding the blank filters, i tryed both Right clicking (like in the changelog) which overwrites like Left click, and Shift click (like on the GUI) which does nothing.

i'm trying to compose the quick bar with smaller pieces, and be able to switch belt types or construction supplies without losing the other filters. 

My username is the same in factorio as it is here 
[Quickbar Templates blank filters.zip](https://github.com/raiguard/Factorio-SmallMods/files/5238823/Quickbar.Templates.blank.filters.zip)

**Comment by raiguard** [comment]
I have no idea how I screwed this up so royally... the logic was completely broken and made no sense. I must have been tired last night.

Anyway, fixed for the next release.
