### ISSUE TITLE
Unable to Import from created blueprint

### ISSUE THREAD

**Issue by Kado-GatorFan12** [raiguard/Factorio-SmallMods#23]
Using the blueprint created from exporting I was unable to import in a different save, the mod is active

I exported on one save, put it into the blueprint holder, switched to second save, and holding the blueprint could not see the button to import.

#### Save file & Username
Kado_GatorFan12 : [Save Game](https://drive.google.com/file/d/1K2gPrxqAPbUXbnhFQA4OEKKNTUicZYLt/view?usp=sharing)

Upload the save file where the bug occurred. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

[Log File](https://drive.google.com/file/d/1dCRdX8eQWmWu6J9Mm2Xgccn-zMYwLlfS/view?usp=sharing)

**Comment by raiguard** [comment]
You can't use blueprints straight from the blueprint library at the moment. This is due to a mod API limitation, and hopefully it will be fixed in Factorio 1.1. For now, you have to move the blueprint into your inventory, then pick it up again, _then_ the button will appear.

**Comment by Kado-GatorFan12** [comment]
I tried that as well
