### ISSUE TITLE
Quickbar templates: Use Blueprint book "Description" field to store references to "My blueprints" library

### ISSUE THREAD

**Issue by jpotelle** [raiguard/Factorio-SmallMods#24]
#### Is your feature request related to a problem? Please describe.

Quickbar templates, like most quickbar mods, cannot save/restore blue/prints/books. Might it be possible to save links to "permanent" items in the "My blueprints" library?

#### Describe the solution you'd like

Just viewing an exported blueprint/template, it appears a 10x10 matrix (array) of constant combinators is used to store the quickbar items. Probably it's quite simple to loop over that and restore item links in the quickbar.

Blueprint books have a "Description" text field. Would it be possible to store a reference to blueprints/book in "my blueprints" library? i.e. with a quickbar #/slot# prefix?
1,9:<text-link/reference-here>
(or some other text-based encoding, e.g. JSON?)
If so, the mod could parse the description field to place the references back into the quickbar upon import.
The mod could verify the existence of the print/book and, it not found, do nothing.

#### Additional context

Thanks for your consideration.

**Comment by raiguard** [comment]
Unfortunately this just isn't possible. Mods are completely unable to read or write blueprint links from/to the quickbar. Believe me, if it was possible, the mod would definitely support it. I'm sorry!

Edit: not to mention that mods don't have access to the blueprint library whatsoever either, as it exists outside of gamestate.
