### ISSUE TITLE
Quickbar template crash

### ISSUE THREAD

**Issue by stheid** [raiguard/Factorio-SmallMods#25]
## Describe the Bug

Quickbar template crashed the server

## Reproduce

no idea

## Version
factorio 1.1.3
qbartemplates 2.2.0

## logs
```
11270.170 Error MainLoop.cpp:1281: Exception at tick 1599005: The mod Quickbar Templates (2.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickbarTemplates::on_player_cursor_stack_changed (ID 29)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__QuickbarTemplates__/control.lua:213: in function <__QuickbarTemplates__/control.lua:198>
11270.173 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod Quickbar Templates (2.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event QuickbarTemplates::on_player_cursor_stack_changed (ID 29)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__QuickbarTemplates__/control.lua:213: in function <__QuickbarTemplates__/control.lua:198>"
11270.173 Info ServerMultiplayerManager.cpp:780: updateTick(1599005) changing state from(InGame) to(Failed)
11270.173 Quitting: multiplayer error.

```

**Comment by raiguard** [comment]
Do you happen to have Krastorio 2 enabled?

**Comment by stheid** [comment]
Yes, we did not know that the mods where incompatible

**Comment by raiguard** [comment]
They're not. The problem is that krastorio was destroying all GUIs in `screen` whenever you open the mini wiki. Update K2 to the latest version and disable / Re-enable quickbar templates to fix the issue.

**Comment by stheid** [comment]
https://mods.factorio.com/mod/Krastorio2/changelog ah, you mean updating to 1.0.13.

I will check that when i have time. I am not sure what exactly you mean with re-enable, but i have already uninstalled your mod and i would reinstall it, however continue to play on a map that was generated with your mod enabled.

In any case, i thank you for your replay. I would close the issue and re-open it in the unlikely case of continuing crashes.
