### ISSUE TITLE
Auto-Load/Save bars string [Quickbar Templates] 

### ISSUE THREAD

**Issue by saaadel** [raiguard/Factorio-SmallMods#26]
#### Is your feature request related to a problem? Please describe.
No. It is just for convenience

#### Describe the solution you'd like
Add per User options, just a raw string. On Start - your mod will auto-import it.
Also, you could add checkbox, replace this string every time user pushed export button.
So, in next game user will get a latest saved string for bars.

#### Additional context
Nothing.

**Comment by raiguard** [comment]
There is already an option to set the default layout. I cannot auto-update it consistently because by default, per-player settings do not carry over between games. You need to change it from the main menu for it to take effect in new games. Sorry!
