### ISSUE TITLE
Export/Import shortcuts buttons support

### ISSUE THREAD

**Issue by saaadel** [raiguard/Factorio-SmallMods#27]
#### Is your feature request related to a problem? Please describe.
Every time I change list of mods, it resets enabled shortcut buttons list and their order (right to bars).

#### Describe the solution you'd like
Could you export/import bars with enabled shortcuts list?
Optional: Add a checkbox into an import dialog to select shortcuts for import.

#### Additional context
/empty/

**Comment by raiguard** [comment]
Sorry, this is just flat-out impossible. Mods cannot access the shortcut bar to tell it what to show / not show. I definitely would do this if I could though.
