### ISSUE TITLE
Placement Guide: Strange cursor when placed last item

### ISSUE THREAD

**Issue by kubiix** [raiguard/Factorio-SmallMods#29]
#### Describe the Bug

When using Placement Guide together with Cursor Enhancements and last building of this type is placed, the cursor in not the plain arrow, but strange violet box appears

#### To Reproduce

1. Craft stone furnace to have 2 of them
2. Select Stonefurnace to place and toggle Placement Guide3
3. Drag to place both furnaces
4. When second is placed, cursor turns weird

#### Save file & Username

kubiix

[Test1.zip](https://github.com/raiguard/Factorio-SmallMods/files/5781499/Test1.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-SmallMods/files/5781513/factorio-current.log)

**Comment by raiguard** [comment]
I'll fix this on the cursor enhancements side.
