### ISSUE TITLE
Non-Recoverable Error with Cursor Enhancements and Placement Guide  

### ISSUE THREAD

**Issue by NotRexButCaesar** [raiguard/Factorio-SmallMods#30]
#### Describe the Bug

Non-recoverable error with Cursor Enhancements and Placement Guide caused by "recalling last item" when that item is a Placement Guide blueprint.

#### To Reproduce

Select mining drill with q
Press the hotkey to create a placement guide
Press q to clear cursor
Press hotkey to recall last item.

[_autosave12.zip](https://github.com/raiguard/Factorio-SmallMods/files/6261713/_autosave12.zip)
AmericanPatriot

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-SmallMods/files/6261717/factorio-current.log)
you might also want my settings?:
[config.zip](https://github.com/raiguard/Factorio-SmallMods/files/6261721/config.zip)

**Comment by NotRexButCaesar** [comment]
https://user-images.githubusercontent.com/68972888/113652751-3c194480-9649-11eb-86d7-cc01b87eca65.mp4

**Comment by raiguard** [comment]
Fixed for the next version.
