### ISSUE TITLE
Add "adjust for show-clock" to StatsGui settings

### ISSUE THREAD

**Issue by Jagholin** [raiguard/Factorio-SmallMods#32]
#### Is your feature request related to a problem? Please describe.

StatsGui already has a setting to adjust its position in case the player uses FPS/UPS indicator.
In recent experimental versions, the devs also added "show-clock" indicator that displays IRL time.
However, it overlaps with StatsGui(see the picture)
![image](https://user-images.githubusercontent.com/4126782/150395518-869b10ca-3642-4143-83d8-4649e6cb9069.png)

#### Describe the solution you'd like

Also add "adjust for show-clock" to the mod settings to shift the display some pixels down.

**Comment by raiguard** [comment]
Implemented for the next release. I've also separated stats GUI into its own repository.
