### ISSUE TITLE
bug on LAN game (Quickbar_Templates 1.0.2)

### ISSUE THREAD

**Issue by cloudziq** [raiguard/Factorio-SmallMods#6]
HI. I encountered an error on a LAN game,  my friend was unable to host a game because of this error:
![IMG_20200429_232209](https://user-images.githubusercontent.com/13541407/80665396-ac166680-8a99-11ea-89a1-e28816fc38dd.jpg)
He fixed it by going to offline game>load - then the game started normally.  After map saving, he was able to host this specific save state, but when I joined minute later - Quickbar Templates throws an error again. Hope this can be fixed :)   For now we both disabled this mod as 'workaround'

**Comment by raiguard** [comment]
You need to update your game to the latest version. I guess I forgot to update the mod's dependency.

Edit: the mod's dependency is fine... if you're on the latest version, then there's something seriously wrong here and it's not my fault.

**Comment by cloudziq** [comment]
hmmm maybe (but not sure) I edited info.json to 0.18.19 I think.  Sorry if that's is not a real bug, but just my action and I forgot about it. 

Also seems like I accidentally created doubled issue :/   Sorry about that too
