### ISSUE TITLE
[1.4.0] Adding QuickItemSearch to an existing game crashes in `on_tick`

### ISSUE THREAD

**Issue by doktorstick** [raiguard/Factorio-SmallMods#8]
Starting my three-day holiday and jumped into Factorio. Lo! An error! 

I did not try it with a new game; it's added to an existing game.. `Rai's Lua Library` is version 0.2.8.

```
Error while running event QuickItemSearch::on_tick (ID 0)
__RaiLuaLib__/lualib/translation.lua:49: attempt to index local 'pt' (a nil value)
stack traceback:
	__RaiLuaLib__/lualib/translation.lua:49: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
```

**Comment by raiguard** [comment]
Thanks for the report! I already knew about this, and it has been solved as a result of some other changes I have made to the next version. That version will release next week with Factorio 0.18.27.

**Comment by raiguard** [comment]
The new version has been released.
